# Generated by Django 5.1.3 on 2024-12-17 03:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Контор', '0002_resident_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('net_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('hoa_monthly', models.DecimalField(decimal_places=2, max_digits=10)),
                ('net_utilities', models.DecimalField(decimal_places=2, max_digits=10)),
                ('water', models.DecimalField(decimal_places=2, max_digits=10)),
                ('electricity', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('failed', 'Failed'), ('in_deficit', 'In-Deficit')], default='pending', max_length=50)),
                ('transaction_id', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('monthly_overview', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Контор.monthlyusage')),
                ('monthly_overview_payment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Контор.utilities')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Контор.resident')),
            ],
        ),
    ]
