# Generated by Django 5.1.2 on 2024-11-13 08:57

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MonthlyUsage',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('water', models.FloatField()),
                ('electricity', models.FloatField()),
                ('monthly_payment', models.FloatField()),
                ('fees', models.FloatField(blank=True, null=True)),
                ('recorded_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='PaymentHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('water_bill', models.FloatField()),
                ('electricity_bill', models.FloatField()),
                ('monthly_payment', models.FloatField()),
                ('fees', models.FloatField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('resident_id', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Utilities',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resident_id', models.IntegerField()),
                ('water_bill', models.FloatField()),
                ('electricity_bill', models.FloatField()),
                ('monthly_payment', models.FloatField()),
                ('fees', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='UtilityRates',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('water_cubic_meter', models.FloatField()),
                ('fixed', models.FloatField()),
                ('taxes', models.FloatField()),
                ('electricity_base', models.FloatField()),
                ('electricity_excess', models.FloatField()),
                ('fixed_e', models.FloatField()),
                ('taxes_e', models.FloatField()),
                ('monthly', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ApartmentBlock',
            fields=[
                ('block_id', models.AutoField(primary_key=True, serialize=False)),
                ('number_of_stories', models.IntegerField()),
                ('units_per_story', models.IntegerField()),
                ('admin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Resident',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('phone_number', models.CharField(max_length=15)),
                ('password', models.CharField(max_length=15)),
                ('story', models.IntegerField()),
                ('unit', models.IntegerField()),
                ('apartment_block', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='residents', to='Контор.apartmentblock')),
            ],
            options={
                'unique_together': {('apartment_block', 'story', 'unit')},
            },
        ),
        migrations.CreateModel(
            name='UsageHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('water_usage', models.FloatField()),
                ('electricity_usage', models.FloatField()),
                ('monthly_payment', models.FloatField()),
                ('fees', models.FloatField()),
                ('recorded_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('apartment_block', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usage_history', to='Контор.apartmentblock')),
                ('resident', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usage_history', to='Контор.resident')),
            ],
        ),
    ]
