# Generated by Django 5.1.4 on 2024-12-17 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Контор', '0002_resident_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymenthistory',
            name='payment_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('failed', 'Failed'), ('in_deficit', 'In-Deficit')], default='pending', max_length=50),
        ),
    ]
