# Generated by Django 5.1.3 on 2024-12-10 07:57

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Контор', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=20)),
                ('lname', models.CharField(max_length=20)),
                ('RD', models.CharField(max_length=20)),
                ('phone_number', models.CharField(max_length=20)),
                ('role', models.CharField(choices=[('Cleaner', 'Cleaner'), ('Utility', 'Utility'), ('Garbage_Man', 'Garbage_Man'), ('Other', 'Other')], default='other', max_length=50)),
                ('staff_salary', models.IntegerField(null=True)),
                ('description', models.CharField(max_length=20)),
                ('since', models.DateTimeField(default=django.utils.timezone.now)),
                ('password', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='BudgetOfApartmentBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('budget_month', models.DateTimeField(default=django.utils.timezone.now)),
                ('total_budget_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('staff_salaries_total', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('resident_utility_total', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('common_property_expenses_total', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('description', models.TextField(blank=True, null=True)),
                ('additional_expenses', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('pretext', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('apartment_block', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='budgetofapartmentblock', to='Контор.apartmentblock')),
            ],
        ),
        migrations.CreateModel(
            name='CommonProperty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('category', models.CharField(choices=[('Structural', 'Structural'), ('Utility', 'Utility'), ('Amenity', 'Amenity'), ('Security', 'Security'), ('Other', 'Other')], default='Other', max_length=50)),
                ('description', models.TextField(blank=True, null=True)),
                ('maintenance_status', models.CharField(choices=[('Good', 'Good'), ('Needs Repair', 'Needs Repair'), ('Under Maintenance', 'Under Maintenance')], default='Good', max_length=50)),
                ('last_maintenance_date', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('block', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='common_properties', to='Контор.apartmentblock')),
            ],
        ),
        migrations.CreateModel(
            name='HOA_members',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('memberName', models.TextField(max_length=25)),
                ('category', models.CharField(choices=[('directors', 'Directors'), ('executive', 'Executive'), ('supervisory', 'Supervisory')], default='other', max_length=50)),
                ('password', models.CharField(max_length=20)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('since', models.DateTimeField()),
                ('members', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hoa_members', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Property_Maintenance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('property_category', models.CharField(max_length=100)),
                ('property_id', models.IntegerField(null=True)),
                ('maintenance_date', models.DateField()),
                ('maintenance_cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('property_image', models.ImageField(blank=True, null=True, upload_to='maintenance_images/')),
                ('on_ground_location', models.CharField(blank=True, max_length=100)),
                ('unit', models.IntegerField(blank=True, null=True)),
                ('story', models.IntegerField(blank=True, null=True)),
                ('next_maintenance_date', models.DateField()),
                ('apartmentblock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Контор.apartmentblock')),
            ],
        ),
        migrations.CreateModel(
            name='Security',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('property_category', models.CharField(choices=[('Structural', 'Structural'), ('Utility', 'Utility'), ('Amenity', 'Amenity'), ('Security', 'Security'), ('Other', 'Other')], default='Other', max_length=50)),
                ('unit', models.CharField(max_length=10, null=True)),
                ('story', models.CharField(max_length=10, null=True)),
                ('type', models.CharField(choices=[('CCTV', 'CCTV Cameras'), ('Security Guard', 'Security Guard'), ('Access Control System', 'Access Control System'), ('Alarm System', 'Alarm System'), ('Other', 'Other')], default='Other', max_length=50)),
                ('location', models.CharField(help_text='Location where the security feature is installed', max_length=255)),
                ('installation_date', models.DateTimeField(blank=True, help_text='Date of installation', null=True)),
                ('condition', models.CharField(choices=[('excellent', 'Excellent'), ('good', 'Good'), ('fair', 'Fair'), ('poor', 'Poor')], default='good', help_text='Condition of the security feature', max_length=50)),
                ('notes', models.TextField(blank=True, help_text='Additional notes or observations about the security feature')),
                ('apartmentblock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='securities_location', to='Контор.apartmentblock')),
            ],
        ),
        migrations.CreateModel(
            name='SharedAmenity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('property_category', models.CharField(choices=[('Structural', 'Structural'), ('Utility', 'Utility'), ('Amenity', 'Amenity'), ('Security', 'Security'), ('Other', 'Other')], default='Other', max_length=50)),
                ('unit', models.CharField(max_length=10, null=True)),
                ('story', models.CharField(max_length=10, null=True)),
                ('amenity_type', models.CharField(choices=[('Public Pool', 'Public Pool'), ('Parking Lot', 'Parking Lot'), ('Stairwell', 'Stairwell'), ('Garbage Chute', 'Garbage Chute')], max_length=50)),
                ('usage_status', models.CharField(choices=[('Available', 'Available'), ('Under Maintenance', 'Under Maintenance'), ('Restricted', 'Restricted')], default='Available', max_length=50)),
                ('last_cleaned_date', models.DateTimeField(blank=True, null=True)),
                ('apartmentblock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='amenities_location', to='Контор.apartmentblock')),
            ],
        ),
        migrations.CreateModel(
            name='PayDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('staff_salary', models.DecimalField(decimal_places=2, max_digits=10)),
                ('description', models.CharField(max_length=100)),
                ('pretext', models.CharField(max_length=50)),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payday', to='HOA.staff')),
            ],
        ),
        migrations.CreateModel(
            name='BudgetRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('request_type', models.CharField(choices=[('General', 'General'), ('Utility', 'Utility'), ('Garbage_Collection', 'Garbage_Collection'), ('Scheduled_Maintenance', 'Scheduled_Maintenance'), ('Other', 'Other')], default='General', max_length=50)),
                ('request_info', models.ImageField(blank=True, null=True, upload_to='budget_requests/')),
                ('pretext', models.CharField(choices=[('Low_on_Supply', 'Low_on_Supply'), ('Broken', 'Broken'), ('Out_of_Date', 'Out_of_Date'), ('Defective', 'Defective'), ('Other', 'Other')], default='Low_on_Supply', max_length=50)),
                ('comment', models.CharField(max_length=150)),
                ('request_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('desicion', models.CharField(choices=[('Approved', 'Approved'), ('Denied', 'Denied')], default='Pending', max_length=50, null=True)),
                ('desicion_comment', models.CharField(max_length=100, null=True)),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='budget_requests', to='HOA.staff')),
            ],
        ),
        migrations.CreateModel(
            name='StaffSalary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('salary_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('month', models.DateTimeField(default=django.utils.timezone.now)),
                ('paid_on', models.DateTimeField(default=django.utils.timezone.now)),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='salaries', to='HOA.staff')),
            ],
        ),
        migrations.CreateModel(
            name='StructuralElement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('property_category', models.CharField(choices=[('Structural', 'Structural'), ('Utility', 'Utility'), ('Amenity', 'Amenity'), ('Security', 'Security'), ('Other', 'Other')], default='Other', max_length=50)),
                ('unit', models.IntegerField(null=True)),
                ('story', models.IntegerField(null=True)),
                ('element_type', models.CharField(choices=[('Exterior Wall', 'Exterior Wall'), ('Load-Bearing Wall', 'Load-Bearing Wall'), ('Roof', 'Roof'), ('Column', 'Column'), ('Basement', 'Basement'), ('Attic', 'Attic')], max_length=50)),
                ('condition', models.CharField(choices=[('Intact', 'Intact'), ('Damaged', 'Damaged'), ('Under Repair', 'Under Repair')], default='Intact', max_length=50)),
                ('inspection_date', models.DateField(blank=True)),
                ('apartmentblock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='structural_elements_location', to='Контор.apartmentblock')),
            ],
        ),
        migrations.CreateModel(
            name='TimeTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('job_type', models.CharField(choices=[('General', 'General'), ('Utility', 'Utility'), ('Garbage_Collection', 'Garbage_Collection'), ('Scheduled_Maintenance', 'Scheduled_Maintenance'), ('Other', 'Other')], default='General', max_length=50)),
                ('job_description', models.CharField(max_length=150)),
                ('attendance', models.CharField(choices=[('Did Not Come To Work', 'Did Not Come To Work'), ('Came To Work', 'Came To Work'), ('Pending / Shift Clock', 'Pending / Shift Clock'), ('Other', 'Other')], default='Pending / Shift Clock', max_length=50)),
                ('job_site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timetables', to='Контор.apartmentblock')),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timetsables', to='HOA.staff')),
            ],
            options={
                'ordering': ['date'],
            },
        ),
        migrations.CreateModel(
            name='UtilitySystem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('property_category', models.CharField(choices=[('Structural', 'Structural'), ('Utility', 'Utility'), ('Amenity', 'Amenity'), ('Security', 'Security'), ('Other', 'Other')], default='Other', max_length=50)),
                ('unit', models.CharField(max_length=10, null=True)),
                ('story', models.CharField(max_length=10, null=True)),
                ('system_type', models.CharField(choices=[('Heating System', 'Heating System'), ('Electricity Supply', 'Electricity Supply'), ('Water Supply', 'Water Supply'), ('Sewage System', 'Sewage System')], max_length=50)),
                ('operational_status', models.CharField(choices=[('Operational', 'Operational'), ('Faulty', 'Faulty'), ('Maintenance Needed', 'Maintenance Needed')], default='Operational', max_length=50)),
                ('last_service_date', models.DateTimeField(blank=True, null=True)),
                ('apartmentblock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='utility_systems_location', to='Контор.apartmentblock')),
            ],
        ),
    ]
