# Generated by Django 5.1.4 on 2024-12-11 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HOA', '0003_remove_budgetrequest_staff_budgetrequest_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='staffsalary',
            name='bank_account',
            field=models.CharField(default=1, max_length=25),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='staffsalary',
            name='bank_type',
            field=models.CharField(choices=[('Khan Bank', 'Khan Bank'), ('Golomt Bank', 'Golomt Bank'), ('TDB', 'TDB'), ('Khas Bank', 'Khas Bank'), ('Other', 'Other')], default='Other', max_length=50),
        ),
    ]
