# Generated by Django 5.1.4 on 2024-12-11 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HOA', '0005_remove_staffsalary_staff_staffsalary_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staffsalary',
            name='bank_account',
            field=models.IntegerField(max_length=25),
        ),
    ]
