# Generated by Django 5.1.4 on 2024-12-11 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HOA', '0006_alter_staffsalary_bank_account'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staffsalary',
            name='bank_account',
            field=models.IntegerField(),
        ),
    ]
